# Variable Group 'workflow-poc-kv001' was defined in the Variables tab
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - azure-terraform/
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

variables:
- group: "workflow-poc-kv001"
- name: vartfazstg-key1
  value: $[variables.tfazstg-key1]
- name: varworkflow-poc-sp-client-id
  value: $[variables.workflow-poc-sp-client-id]
- name: varworkflow-poc-sp-tenant-id
  value: $[variables.workflow-poc-sp-tenant-id]
- name: varworkflow-poc-sp-secret
  value: $[variables.workflow-poc-sp-secret]  

jobs:
- job: Job_1
  displayName: Terraform Plan
  pool:
    vmImage: ubuntu-18.04
  steps:
  - checkout: self
    clean: true
  - task: TerraformInstaller@0
    displayName: Install Terraform 1.1.1
    inputs:
      terraformVersion: 1.1.1
  - task: CmdLine@2
    displayName: Terrafirm init
    inputs:
      script: |
        echo $ARM_ACCESS_KEY
        terraform init -backend-config="access_key=${vartfazstg-key1}"
      workingDirectory: azure_infrastructure
    env:
      ARM_ACCESS_KEY: "nXQbcLmgaIIXVIvmL5lsV11JUmmpN7Q6VltL+/Q8dh5xC9QjbrM5djrEe91QFqChj1XWYm9ti5T3+2GY1m7UXw=="
  - task: CmdLine@2
    displayName: Terrafrom validate
    inputs:
      script: terraform validate
      workingDirectory: azure_infrastructure
  - task: CmdLine@2
    displayName: Terrafrom plan
    inputs:
      script: terraform plan -input=false -out=tfplan -var="workflow-poc-sp-client-id=$(varworkflow-poc-sp-client-id)" -var="workflow-poc-sp-secret=$(varworkflow-poc-sp-secret)" -var="workflow-poc-sp-tenant-id=$(varworkflow-poc-sp-tenant-id)"
      workingDirectory: azure_infrastructure
  - task: ArchiveFiles@2
    displayName: Archive Terraform Plan
    inputs:
      rootFolderOrFile: azure_infrastructure
      archiveType: tar
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-tfplan.tgz
  - task: PublishPipelineArtifact@1
    displayName: Publish Terraform Plan
    inputs:
      path: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-tfplan.tgz
      artifactName: $(Build.BuildId)-tfplan.tgz
