# Variable Group 'workflow-poc-kv001' was defined in the Variables tab

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - azure_infrastructure/*

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Job_1
    displayName: Terraform Plan
    steps:
    - checkout: self
      clean: true
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'workflow-poc-sp'
        KeyVaultName: 'workflow-poc-kv001'
        SecretsFilter: '*'
        RunAsPreJob: false
    - task: TerraformInstaller@0
      displayName: Install Terraform 1.1.1
      inputs:
        terraformVersion: 1.1.1
    - task: CmdLine@2
      displayName: Terrafirm init
      inputs:
        script: terraform init -backend-config="access_key=$(tfazstg-key1)"
        workingDirectory: azure_infrastructure
      # env:
      #   ARM_ACCESS_KEY: "nXQbcLmgaIIXVIvmL5lsV11JUmmpN7Q6VltL+/Q8dh5xC9QjbrM5djrEe91QFqChj1XWYm9ti5T3+2GY1m7UXw=="
    - task: CmdLine@2
      displayName: Terrafrom validate
      inputs:
        script: terraform validate
        workingDirectory: azure_infrastructure
    - task: CmdLine@2
      displayName: Terrafrom plan
      inputs:
        script: terraform plan -input=false -out=tfplan -var="workflow-poc-sp-client-id=$(workflow-poc-sp-client-id)" -var="workflow-poc-sp-secret=$(workflow-poc-sp-secret)" -var="workflow-poc-sp-tenant-id=$(workflow-poc-sp-tenant-id)" -var="env=$(ENVIRONMENT)"
        workingDirectory: azure_infrastructure
    - task: ArchiveFiles@2
      displayName: Archive Terraform Plan
      inputs:
        rootFolderOrFile: azure_infrastructure
        archiveType: tar
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-tfplan.tgz
    - task: PublishPipelineArtifact@1
      displayName: Publish Terraform Plan
      inputs:
        path: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-tfplan.tgz
        artifactName: $(Build.BuildId)-tfplan.tgz

- stage: Apply
  dependsOn: Build
  jobs:
  - deployment: apply
    displayName: Terraform Apply
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'workflow-poc-sp'
              KeyVaultName: 'workflow-poc-kv001'
              SecretsFilter: '*'
              RunAsPreJob: false
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: '$(Build.BuildId)-tfplan.tgz'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: ExtractFiles@1
            displayName: 'Extract files '
            inputs:
              archiveFilePatterns: $(System.ArtifactsDirectory)/$(Build.BuildId)-tfplan.tgz
              destinationFolder: $(System.DefaultWorkingDirectory)/terraform
              cleanDestinationFolder: false
          - task: TerraformInstaller@0
            displayName: Install Terraform 1.1.1
            inputs:
              terraformVersion: 1.1.1
          - task: CmdLine@2
            displayName: Terraform Init
            inputs:
              script: terraform init -backend-config="access_key=$(tfazstg-key1)"
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform/azure_infrastructure/
          - task: CmdLine@2
            displayName: Terraform Apply
            inputs:
              script: terraform apply -auto-approve -input=false tfplan
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform/azure_infrastructure/